name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          PACKAGE_JSON_PATH="${{ github.workspace }}/coffee-shops/package.json"
          PACKAGE_LOCK_PATH="${{ github.workspace }}/coffee-shops/package-lock.json"
          if [ -f "$PACKAGE_JSON_PATH" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            if [ ! -f "$PACKAGE_LOCK_PATH" ]; then
              echo "package-lock.json not found"
              exit 1
            fi
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: List files for debug
        run: ls -la coffee-shops

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            coffee-shops/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('coffee-shops/package-lock.json') }}-${{ hashFiles('coffee-shops/**/*.[jt]s', 'coffee-shops/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('coffee-shops/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci --prefix coffee-shops

      - name: Build with Next.js
        run: npx next build --prefix coffee-shops

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: coffee-shops/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
